import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import Drawer from "@/components/Navbar/Drawer";
import SearchBar from "@/components/Navbar/SearchBar";
import ReduxProvider from "@/src/redux/Provider";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body lang="en"  className="relative min-h-full flex flex-col ">

        <ReduxProvider>
          
          <Drawer/>
          <NavBar/>
          <SearchBar/>
          
          {children}

          <Footer/>

        </ReduxProvider>
        
        </body>
    </html>
  );
}
